import uuid
from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import enum

# Python enum for visit modes - inferred automatically by detectarMode()
class Mode(str, enum.Enum):
    REMOT = "REMOT"
    GUIAT = "GUIAT"
    LLIURE = "LLIURE"

class Visita(Base):
    __tablename__ = "visita"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # timestamp generated by PostgreSQL at insert time
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    # mode inferred automatically - not provided by the user
    mode = Column(SAEnum(Mode), nullable=False)

    # foreign keys - associative class between visitant and parada
    usuari_id = Column(UUID(as_uuid=True), ForeignKey("usuari.id"), nullable=False)
    parada_id = Column(UUID(as_uuid=True), ForeignKey("parada.id"), nullable=False)

    # relationships
    usuari = relationship("Usuari", back_populates="visites")
    parada = relationship("Parada", back_populates="visites")