"""create initial tables

Revision ID: 41bf3689e0ea
Revises: 
Create Date: 2026-05-05 17:22:11.740243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bf3689e0ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autora',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('cognom', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('anys_vida', sa.String(), nullable=True),
    sa.Column('foto_minio_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('nom_espai', sa.String(), nullable=False),
    sa.Column('coordenades', sa.Enum('BALCO_MEDITERRANI', 'AMFITEATRE_ROMA', 'PL_FONT', 'PL_SEDASSOS', 'ESCALES_CATEDRAL', 'C_CAVALLERS', 'PORTAL_ROSER', 'C_DAMES', 'PL_PALLOL', 'C_SANT_LLORENC', name='coordenadesparada'), nullable=False),
    sa.Column('foto_minio_key', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre')
    )
    op.create_table('usuari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('cognom', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('idioma', sa.Enum('CA', 'ES', 'EN', name='idioma'), nullable=False),
    sa.Column('rol', sa.Enum('VISITANT', 'EDITOR', 'ADMINISTRADOR', name='rolusuari'), nullable=False),
    sa.Column('data_registre', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actiu', sa.Boolean(), nullable=False),
    sa.Column('procedencia', sa.String(), nullable=True),
    sa.Column('es_alumne', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuari_email'), 'usuari', ['email'], unique=True)
    op.create_table('comentari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contingut', sa.String(), nullable=False),
    sa.Column('data_creacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuari_id', sa.UUID(), nullable=False),
    sa.Column('parada_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parada_id'], ['parada.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titol', sa.String(), nullable=False),
    sa.Column('obra_origen', sa.String(), nullable=True),
    sa.Column('contingut', sa.String(), nullable=False),
    sa.Column('parada_id', sa.UUID(), nullable=False),
    sa.Column('autora_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['autora_id'], ['autora.id'], ),
    sa.ForeignKeyConstraint(['parada_id'], ['parada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mode', sa.Enum('REMOT', 'GUIAT', 'LLIURE', name='mode'), nullable=False),
    sa.Column('usuari_id', sa.UUID(), nullable=False),
    sa.Column('parada_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parada_id'], ['parada.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('usuari_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('data_creacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuari.id'], ),
    sa.PrimaryKeyConstraint('usuari_id', 'text_id')
    )
    op.create_table('recurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipus', sa.Enum('AUDIO', 'VIDEO', name='tipusrecurs'), nullable=False),
    sa.Column('minio_key', sa.String(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurs')
    op.drop_table('like')
    op.drop_table('visita')
    op.drop_table('text')
    op.drop_table('comentari')
    op.drop_index(op.f('ix_usuari_email'), table_name='usuari')
    op.drop_table('usuari')
    op.drop_table('parada')
    op.drop_table('autora')
    # ### end Alembic commands ###
