"""add autora_traduccio

Revision ID: 6601375028bc
Revises: 807d577b294e
Create Date: 2026-08-26 22:21:00.377832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6601375028bc'
down_revision: Union[str, Sequence[str], None] = '807d577b294e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # El tipus `idioma` ja existeix: el va crear la migracio inicial per a
    # usuari.idioma. Amb create_type=True -el que genera l'autogenerate- aquesta
    # migracio provaria de tornar-lo a crear i petaria amb "type already exists".
    idioma = postgresql.ENUM('CA', 'ES', 'EN', name='idioma', create_type=False)

    op.create_table(
        'autora_traduccio',
        sa.Column('autora_id', sa.UUID(), nullable=False),
        sa.Column('idioma', idioma, nullable=False),
        sa.Column('bio', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['autora_id'], ['autora.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('autora_id', 'idioma'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autora_traduccio')
    # ### end Alembic commands ###
